# Generated by Django 2.2 on 2020-04-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edit_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
